version: '3.8'

services:
  db:
    image: postgres:15
    container_name: student_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - student_network

  api:
    build: ./student-be
    container_name: student_api
    env_file:
      - ./student-be/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - student_network
    volumes:
      - ./student-be:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build: ./student-fe
    container_name: student_web
    env_file:
      - ./student-fe/.env
    ports:
      - "3000:80"
    networks:
      - student_network
    depends_on:
      - api

volumes:
  postgres_data:

networks:
  student_network:
    driver: bridge
