version: '3.8'

services:
  db:
    image: postgres:15
    container_name: student_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - student_network

  api:
    build: .
    container_name: student_api
    environment:
      DATABASE_URL: postgresql://student_user:student_password@db:5432/student_db
      SECRET_KEY: your-secret-key-for-production
      DEBUG: "false"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - student_network
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

networks:
  student_network:
    driver: bridge
